#spring:
#  datasource:
#    url: jdbc:hsqldb:mem:testDB
#    username: sa
#    password: sa
#  jpa:
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true

#spring:
#  data:
#    mongodb:
#      uri: mongodb+srv://anuishan:9897@cluster0.m0ejaho.mongodb.net/chatApp?retryWrites=true&w=majority
#

spring:
  data:
    mongodb:
      uri: mongodb+srv://anuishan:9897@cluster0.m0ejaho.mongodb.net/chatApp?retryWrites=true&w=majority



  main:
    allow-circular-references: true